spring:
  application:
    name: rest-path-server

server:
  port: 8070


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 4000

city:
  custom:
    url: http://localhost:9093/cities
  default:
    url: http://city-rout-handler/cities

#eureka:
#  client:
#    service-url:
#      defaulstZone: http://localhost:8767/eureka
